OPENAI_API_KEY = "*************************************************"
HUGGINGFACEHUB_API_TOKEN = "******************************"
ELEVENLABS_API_KEY="*****************************************"
TOGETHER_API_KEY="*******************************************"